server.port = 8083
spring.application.name=order

spring.datasource.url=jdbc:h2:mem:Order;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=7235B079C0C1F3D3294340D18D675C525C415F46B85BC88CD3D96A6528A3783B
eureka.client.service-Url.defaultZone=http://eureka:8761/eureka/